#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    

    x=int(input().strip())
y=x%2
if y!=0 : print('Weird')
elif y==0 and x>=2 and x<=5 or x>20: print ('Not Weird')
elif y==0 and x>=2 and x<=20: print ('Weird')
